services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    hostname: tailscale-subnet
    restart: unless-stopped

    network_mode: "host"

    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun

    volumes:
      - /mnt/data/docker/tailscale/data:/var/lib/tailscale

    env_file:
      - /mnt/data/secrets/tailscale/auth.env

    environment:
      - TS_USERSPACE=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--advertise-routes=192.168.1.0/24,10.1.1.0/24 --advertise-tags=tag:subnet-router