services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/data/docker/jellyfin/config:/config
      - /mnt/data/docker/jellyfin/cache:/cache
      - /mnt/data/samba:/media:ro
    restart: unless-stopped
#    networks: [edge]
#
#networks:
#  edge:
#    external: true